modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0"
showAsResourcePack=false

[[mods]]
modId="beginnersdelight"
version="${version}"
displayName="Beginner's Delight"
description='''
Generates a small base structure at the world spawn point to help beginners proceed safely through early-game adventures.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/BeginnersDelight"

[[dependencies.beginnersdelight]]
modId="forge"
mandatory=true
versionRange="[36.2.34,)"
ordering="NONE"
side="BOTH"

[[dependencies.beginnersdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
